# k8s service를 활용한 nodeport 설정
apiVersion: v1
kind: Service
metadata:
  name: devops-django-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: devops-django-app