name: apiserver-django

on:
  push:
    branches: ["main"]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ secrets.DOCKERHUB_REPOSITORY }}  # Docker Hub 리포지토리 이름
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  # Docker Hub 사용자 이름
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}     # Docker Hub 비밀번호/토큰

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Check Python version
        run: python --version

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t $REPO_NAME:1.0 ./apiserver

      - name: Push Docker image to Docker Hub
        run: docker push $REPO_NAME:1.0
